"""Technique #8: AI-generated extraction payloads — LLM generates novel prompts."""
import logging
from ..techniques.base import ExtractionTechnique, TechniqueResult
from ..core.payload_generator import PayloadGenerator
from ..output.formatter import score_confidence, clean_extraction

logger = logging.getLogger("promptleak")


class AIGeneratedTechnique(ExtractionTechnique):
    name = "ai_generated"
    description = "Uses an LLM to generate novel extraction payloads — AI hacking AI"

    def __init__(self, provider: str = "openai", model: str = "gpt-4o-mini",
                 api_key: str = None, base_url: str = None):
        super().__init__()
        self.generator = PayloadGenerator(provider=provider, model=model,
                                          api_key=api_key, base_url=base_url)

    async def execute(self, page, target) -> TechniqueResult:
        # Check cache first for previously successful payloads
        cached_payloads = self.generator.load_cache()
        best_confidence = 0.0
        best_output = ""
        last_error = None

        if cached_payloads:
            logger.info(f"Found {len(cached_payloads)} cached successful payloads")
            for entry in cached_payloads[:3]:
                payload = entry["text"]
                logger.info(f"Trying cached payload: {payload[:80]}...")
                response = await self._send_prompt(page, target, payload)
                if response:
                    cleaned = clean_extraction(response, payload)
                    conf = score_confidence(cleaned)
                    if conf > best_confidence:
                        best_confidence = conf
                        best_output = response
                    if conf > 0.7:
                        self.generator.save_to_cache(payload, conf, target.name)
                        break

        if best_confidence >= 0.7:
            return TechniqueResult(
                technique_name=self.name,
                success=True,
                raw_output=best_output,
                cleaned_output=clean_extraction(best_output, ""),
                confidence=best_confidence,
                metadata={"source": "cache", "payloads_tried": len(cached_payloads[:3])},
            )

        # Generate fresh payloads from LLM
        logger.info("Generating novel payloads via LLM...")
        payloads = await self.generator.generate_payloads(intent="extract system prompt", count=5)

        if not payloads:
            return TechniqueResult(
                technique_name=self.name,
                success=False,
                raw_output="",
                cleaned_output="",
                confidence=0.0,
                error="No payloads generated by LLM",
            )

        for payload in payloads:
            logger.info(f"Testing AI-generated payload: {payload[:80]}...")
            response = await self._send_prompt(page, target, payload)
            if response:
                cleaned = clean_extraction(response, payload)
                conf = score_confidence(cleaned)
                if conf > best_confidence:
                    best_confidence = conf
                    best_output = response
                if conf > 0.5:
                    self.generator.save_to_cache(payload, conf, target.name)

        if best_confidence > 0:
            return TechniqueResult(
                technique_name=self.name,
                success=True,
                raw_output=best_output,
                cleaned_output=clean_extraction(best_output, ""),
                confidence=best_confidence,
                metadata={"source": "llm_generated", "payloads_generated": len(payloads)},
            )

        return TechniqueResult(
            technique_name=self.name,
            success=False,
            raw_output="",
            cleaned_output="",
            confidence=0.0,
            error=last_error or "All generated payloads failed to extract",
        )
